### ISSUE TITLE
Proposing name change of project

### ISSUE THREAD

**Issue by jeroenrinzema** [sysco-middleware/KGO#3]
I want to propose to change the name of this project to  **KADI** (kafka data insight). This could serve as a cover name for the project.

**Comment by jeqo** [comment]
Let's iterate on the purpose to check if "data insight" match with it. Initially, would be to cover more than `schema-registry` right?

**Comment by jeroenrinzema** [comment]
Yes, I would also like to include modules as: topics, topology and maybe even projects such as KSQL.

**Comment by jeqo** [comment]
What about having separate modules? Will that be to much boilerplate probably? We could manage them independly and wrap them up. - e.g `confluent-schema-registry-ui`
On the other side, if we grab them on the same UI, maybe something related with Confluent platform could give more idea about the project (thinking out loud) - e.g. `confluent-ui`

**Comment by jeroenrinzema** [comment]
We could create separate modules but this would limit our plausibilities in the future. Maybe we want to create a KSQL module that uses the topics module to show the messages in a given topic. Modules can be enabled and disabled via the config file so you only see what you need.

We could brainstorm a bit more about the name. I used the following [acronym generator](http://acronymcreator.net/ace.py) to come up with the acronym KADI.

**Comment by jeqo** [comment]
@jeroenrinzema I like the proposal. `Insight` is the only part that does not close for me, as we are doing more management/governance on top of the streaming platform than getting insight from flowing data, as the name implies.

**Comment by jeroenrinzema** [comment]
@jeqo And what about KAMA (kafka management)?

**Comment by jeroenrinzema** [comment]
@jeqo @NikitaZhevnitskiy what do you guys think about the name `KAGO` (Kafka Governance)?

**Comment by jeqo** [comment]
@jeroenrinzema, like it, what about kg?
